services:
  server-logiflowerp-logistica:
    container_name: server-logiflowerp-logistica
    image: logiflowerp/server-logiflowerp-logistica:latest
    env_file:
     - ./.env
    environment:
      NODE_ENV: production
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true