export const WAREHOUSE_EXIT_TYPES = {
    RepositoryMongo: Symbol('RepositoryMongo'),
    UseCaseFind: Symbol('UseCaseFind'),
    UseCaseGetAll: Symbol('UseCaseGetAll'),
    UseCaseDeleteOne: Symbol('UseCaseDeleteOne'),
    UseCaseInsertOne: Symbol('UseCaseInsertOne'),
    UseCaseValidate: Symbol('UseCaseValidate'),
    UseCaseAddDetail: Symbol('UseCaseAddDetail'),
    UseCaseDeleteDetail: Symbol('UseCaseDeleteDetail'),
    UseCaseAddSerial: Symbol('UseCaseAddSerial'),
    UseCaseDeleteSerial: Symbol('UseCaseDeleteSerial'),
    UseCaseAutomaticReplenishmentToa: Symbol('UseCaseAutomaticReplenishmentToa'),
    UseCaseAutomaticReplenishmentWin: Symbol('UseCaseAutomaticReplenishmentWin'),
    UseCaseEditAmountDetail: Symbol('UseCaseEditAmountDetail'),
    UseCaseBulkExit: Symbol('UseCaseBulkExit'),
    UseCaseAddDetailBySerial: Symbol('UseCaseAddDetailBySerial'),
}