export const SHARED_TYPES = {
    AdapterMongoDB: Symbol.for('AdapterMongoDB'),
    AdapterToken: Symbol.for('AdapterToken'),
    AdapterSocket: Symbol.for('AdapterSocket'),
    AdapterRedis: Symbol.for('AdapterRedis'),
    AdapterMail: Symbol.for('AdapterMail'),
    AdapterApiRequest: Symbol.for('AdapterApiRequest'),
    AdapterRabbitMQ: Symbol.for('AdapterRabbitMQ'),
    database_logiflow: Symbol.for('database_logiflow'),
    collection_movements: Symbol.for('collection_movements'),
    collection_productGroups: Symbol.for('collection_productGroups'),
    collection_endpoint: Symbol.for('collection_endpoint'),
    collection_systemOptions: Symbol.for('collection_systemOptions'),
    collection_products: Symbol.for('collection_products'),
    BuildSystemOptionService: Symbol.for('BuildSystemOptionService'),
    collection_productPrices: Symbol.for('collection_productPrices'),
    collection_unitOfMeasures: Symbol.for('collection_unitOfMeasures'),
    collection_stores: Symbol.for('collection_stores'),
}