export const WAREHOUSE_RETURN_TYPES = {
    RepositoryMongo: Symbol('RepositoryMongo'),
    UseCaseFind: Symbol('UseCaseFind'),
    UseCaseGetAll: Symbol('UseCaseGetAll'),
    UseCaseDeleteOne: Symbol('UseCaseDeleteOne'),
    UseCaseInsertOne: Symbol('UseCaseInsertOne'),
    UseCaseValidate: Symbol('UseCaseValidate'),
    UseCaseAddDetail: Symbol('UseCaseAddDetail'),
    UseCaseDeleteDetail: Symbol('UseCaseDeleteDetail'),
    UseCaseAddSerial: Symbol('UseCaseAddSerial'),
    UseCaseDeleteSerial: Symbol('UseCaseDeleteSerial'),
    UseCaseFindIndividual: Symbol('UseCaseFindIndividual'),
    UseCaseInsertOneDraft: Symbol('UseCaseInsertOneDraft'),
    UseCaseRegister: Symbol('UseCaseRegister'),
}